/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dacs1;

import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import project.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Calendar;


/**
 *
 * @author ASUS
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        tfCheckINDateCCI.setEditable(false);
        tfPriceCCI.setEditable(false);
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        tfCheckINDateCCI.setText(myFormat.format(cal.getTime()));
    }
    
    String bed;
    String roomType;
    String roomNo;
    String price;
    
    public void roomDetails()
    {
        cbRoomNumCCI.removeAllItems();
        tfPriceCCI.setText("");
        bed = (String)cbBedCCI.getSelectedItem();
        roomType = (String)cbRoomTypeCCI.getSelectedItem();
        try
        {
            ResultSet rs = Select.getData("select * from room where bed = '"+bed+"' and roomType = '"+roomType+"' and status = 'Not Booked'");
            while(rs.next())
            {
                cbRoomNumCCI.addItem(rs.getString(1));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    int witdth = 250;
    int height = 768;

    void openMenubar() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < witdth; i++) {
                    jpnSlideMenu.setSize(i, height);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    void closeMenubar() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = witdth; i > 0; i--) {
                    jpnSlideMenu.setSize(i, height);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    private void refreshRoomTable() {
        DefaultTableModel model = (DefaultTableModel) jtbManageRoom.getModel();
        model.setRowCount(0); // Xóa hết các dòng hiện tại trên bảng

        // Lấy dữ liệu từ cơ sở dữ liệu và thêm vào bảng
        ResultSet rs = Select.getData("SELECT * FROM room");
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnContainer = new javax.swing.JPanel();
        jpnSlideMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbCloseMenu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbManageRoom = new javax.swing.JLabel();
        lbCustomerCheckIn = new javax.swing.JLabel();
        lbCustomerCheckOut = new javax.swing.JLabel();
        lbCustomerDetailsBill = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbLogout = new javax.swing.JLabel();
        lbHomePage = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jpnMenuBar = new javax.swing.JPanel();
        lbOpenMenu = new javax.swing.JLabel();
        jpnMain = new javax.swing.JPanel();
        cardTrangchu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cardManageRoom = new javax.swing.JPanel();
        kGPBackground1 = new com.k33ptoo.components.KGradientPanel();
        lbMRLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbManageRoom = new javax.swing.JTable();
        lbRoomNumberM = new javax.swing.JLabel();
        tfRoomNumberM = new javax.swing.JTextField();
        lbRoomTypeM = new javax.swing.JLabel();
        cbRoomTypeM = new javax.swing.JComboBox<>();
        lbBedM = new javax.swing.JLabel();
        cbBedM = new javax.swing.JComboBox<>();
        lbPriceM = new javax.swing.JLabel();
        tfPriceM = new javax.swing.JTextField();
        kbtnAddRoom = new com.k33ptoo.components.KButton();
        cardCustomerCheckIn = new javax.swing.JPanel();
        kGPBackground2 = new com.k33ptoo.components.KGradientPanel();
        lbCCILogo = new javax.swing.JLabel();
        lbNameCCI = new javax.swing.JLabel();
        tfNameCCI = new javax.swing.JTextField();
        lbMobileNumCCI = new javax.swing.JLabel();
        tfMobileNumCCI = new javax.swing.JTextField();
        lbNationalityCCI = new javax.swing.JLabel();
        tfNationalityCCI = new javax.swing.JTextField();
        lbGenderCCI = new javax.swing.JLabel();
        cbGenderCCI = new javax.swing.JComboBox<>();
        lbEmailCCI = new javax.swing.JLabel();
        tfEmailCCI = new javax.swing.JTextField();
        lbIDProofCCI = new javax.swing.JLabel();
        tfIDProofCCI = new javax.swing.JTextField();
        lbAddressCCI = new javax.swing.JLabel();
        tfAddressCCI = new javax.swing.JTextField();
        lbCheckINDateCCI = new javax.swing.JLabel();
        tfCheckINDateCCI = new javax.swing.JTextField();
        lbBedCCI = new javax.swing.JLabel();
        cbBedCCI = new javax.swing.JComboBox<>();
        lbRoomTypeCCI = new javax.swing.JLabel();
        cbRoomTypeCCI = new javax.swing.JComboBox<>();
        lbRoomNumCCI = new javax.swing.JLabel();
        cbRoomNumCCI = new javax.swing.JComboBox<>();
        lbPriceCCI = new javax.swing.JLabel();
        tfPriceCCI = new javax.swing.JTextField();
        kbtnAlloteRoomCCI = new com.k33ptoo.components.KButton();
        kbtnClearCCI = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnContainer.setBackground(new java.awt.Color(255, 255, 255));
        jpnContainer.setMinimumSize(new java.awt.Dimension(1366, 768));
        jpnContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnSlideMenu.setBackground(new java.awt.Color(204, 255, 255));
        jpnSlideMenu.setMinimumSize(new java.awt.Dimension(250, 768));
        jpnSlideMenu.setPreferredSize(new java.awt.Dimension(250, 768));
        jpnSlideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/avatar.png"))); // NOI18N

        lbCloseMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        lbCloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCloseMenuMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setText("Livin Hotel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(lbCloseMenu)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jpnSlideMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 200));

        lbManageRoom.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        lbManageRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage room.png"))); // NOI18N
        lbManageRoom.setText("Manage Room");
        lbManageRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbManageRoomMouseClicked(evt);
            }
        });
        jpnSlideMenu.add(lbManageRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        lbCustomerCheckIn.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        lbCustomerCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Registration & Check IN.png"))); // NOI18N
        lbCustomerCheckIn.setText("Customer Check In");
        lbCustomerCheckIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCustomerCheckInMouseClicked(evt);
            }
        });
        jpnSlideMenu.add(lbCustomerCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        lbCustomerCheckOut.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        lbCustomerCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Check Out.png"))); // NOI18N
        lbCustomerCheckOut.setText("Customer Check Out");
        jpnSlideMenu.add(lbCustomerCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        lbCustomerDetailsBill.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        lbCustomerDetailsBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Details Bill.png"))); // NOI18N
        lbCustomerDetailsBill.setText("Customer Details Bill");
        jpnSlideMenu.add(lbCustomerDetailsBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));
        jpnSlideMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 250, 10));

        lbLogout.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        lbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        lbLogout.setText("Logout");
        jpnSlideMenu.add(lbLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, -1, -1));

        lbHomePage.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        lbHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Check Out.png"))); // NOI18N
        lbHomePage.setText("Home");
        lbHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHomePageMouseClicked(evt);
            }
        });
        jpnSlideMenu.add(lbHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(102, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        jpnSlideMenu.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 768));

        jpnContainer.add(jpnSlideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 768));

        jpnMenuBar.setBackground(new java.awt.Color(255, 255, 255));
        jpnMenuBar.setPreferredSize(new java.awt.Dimension(1366, 100));

        lbOpenMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        lbOpenMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOpenMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnMenuBarLayout = new javax.swing.GroupLayout(jpnMenuBar);
        jpnMenuBar.setLayout(jpnMenuBarLayout);
        jpnMenuBarLayout.setHorizontalGroup(
            jpnMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuBarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbOpenMenu)
                .addContainerGap(1301, Short.MAX_VALUE))
        );
        jpnMenuBarLayout.setVerticalGroup(
            jpnMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbOpenMenu)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jpnContainer.add(jpnMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, 60));

        jpnMain.setLayout(new java.awt.CardLayout());

        cardTrangchu.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N

        javax.swing.GroupLayout cardTrangchuLayout = new javax.swing.GroupLayout(cardTrangchu);
        cardTrangchu.setLayout(cardTrangchuLayout);
        cardTrangchuLayout.setHorizontalGroup(
            cardTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTrangchuLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        cardTrangchuLayout.setVerticalGroup(
            cardTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTrangchuLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnMain.add(cardTrangchu, "card2");

        cardManageRoom.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cardManageRoomComponentShown(evt);
            }
        });

        kGPBackground1.setkBorderRadius(0);
        kGPBackground1.setkEndColor(new java.awt.Color(102, 255, 153));
        kGPBackground1.setkGradientFocus(900);
        kGPBackground1.setkStartColor(new java.awt.Color(51, 153, 255));
        kGPBackground1.setOpaque(false);

        lbMRLogo.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        lbMRLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage room.png"))); // NOI18N
        lbMRLogo.setText("Manage Room");

        jtbManageRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Bed", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(jtbManageRoom);

        lbRoomNumberM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRoomNumberM.setText("Room Number:");

        tfRoomNumberM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbRoomTypeM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRoomTypeM.setText("RoomType:");

        cbRoomTypeM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbRoomTypeM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "None-AC" }));

        lbBedM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbBedM.setText("Bed:");

        cbBedM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbBedM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));

        lbPriceM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPriceM.setText("Price:");

        tfPriceM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        kbtnAddRoom.setText("Add Room");
        kbtnAddRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kbtnAddRoom.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        kbtnAddRoom.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kbtnAddRoom.setkHoverStartColor(new java.awt.Color(153, 255, 0));
        kbtnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtnAddRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGPBackground1Layout = new javax.swing.GroupLayout(kGPBackground1);
        kGPBackground1.setLayout(kGPBackground1Layout);
        kGPBackground1Layout.setHorizontalGroup(
            kGPBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGPBackground1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbMRLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kGPBackground1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(kGPBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbRoomNumberM)
                    .addComponent(tfRoomNumberM)
                    .addComponent(lbRoomTypeM)
                    .addComponent(lbBedM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPriceM)
                    .addComponent(kbtnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPriceM)
                    .addComponent(cbRoomTypeM, 0, 465, Short.MAX_VALUE)
                    .addComponent(cbBedM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        kGPBackground1Layout.setVerticalGroup(
            kGPBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGPBackground1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lbMRLogo)
                .addGap(31, 31, 31)
                .addGroup(kGPBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGPBackground1Layout.createSequentialGroup()
                        .addComponent(lbRoomNumberM)
                        .addGap(18, 18, 18)
                        .addComponent(tfRoomNumberM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbRoomTypeM)
                        .addGap(18, 18, 18)
                        .addComponent(cbRoomTypeM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(lbBedM)
                        .addGap(18, 18, 18)
                        .addComponent(cbBedM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(lbPriceM)
                        .addGap(18, 18, 18)
                        .addComponent(tfPriceM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kbtnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardManageRoomLayout = new javax.swing.GroupLayout(cardManageRoom);
        cardManageRoom.setLayout(cardManageRoomLayout);
        cardManageRoomLayout.setHorizontalGroup(
            cardManageRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGPBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardManageRoomLayout.setVerticalGroup(
            cardManageRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGPBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnMain.add(cardManageRoom, "card3");

        kGPBackground2.setkBorderRadius(0);
        kGPBackground2.setkEndColor(new java.awt.Color(102, 255, 153));
        kGPBackground2.setkGradientFocus(900);
        kGPBackground2.setkStartColor(new java.awt.Color(51, 153, 255));
        kGPBackground2.setPreferredSize(new java.awt.Dimension(1370, 710));

        lbCCILogo.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        lbCCILogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Registration & Check IN.png"))); // NOI18N
        lbCCILogo.setText("Customer Check In");

        lbNameCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNameCCI.setText("Name:");

        tfNameCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbMobileNumCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMobileNumCCI.setText("Mobile Number:");

        tfMobileNumCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbNationalityCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNationalityCCI.setText("Nationality:");

        tfNationalityCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbGenderCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbGenderCCI.setText("Gender:");

        cbGenderCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbGenderCCI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        lbEmailCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEmailCCI.setText("Email:");

        tfEmailCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbIDProofCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbIDProofCCI.setText("ID Proof:");

        tfIDProofCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbAddressCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAddressCCI.setText("Address:");

        tfAddressCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbCheckINDateCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCheckINDateCCI.setText("Check IN Date (Today):");

        tfCheckINDateCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbBedCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbBedCCI.setText("Bed:");

        cbBedCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbBedCCI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));

        lbRoomTypeCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRoomTypeCCI.setText("Room Type:");

        cbRoomTypeCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbRoomTypeCCI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "None-AC" }));

        lbRoomNumCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRoomNumCCI.setText("Room Number:");

        cbRoomNumCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbPriceCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPriceCCI.setText("Price:");

        tfPriceCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        kbtnAlloteRoomCCI.setText("Allote Room");
        kbtnAlloteRoomCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kbtnAlloteRoomCCI.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        kbtnAlloteRoomCCI.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kbtnAlloteRoomCCI.setkHoverStartColor(new java.awt.Color(153, 255, 0));

        kbtnClearCCI.setText("Clear");
        kbtnClearCCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kbtnClearCCI.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        kbtnClearCCI.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kbtnClearCCI.setkHoverStartColor(new java.awt.Color(153, 255, 0));

        javax.swing.GroupLayout kGPBackground2Layout = new javax.swing.GroupLayout(kGPBackground2);
        kGPBackground2.setLayout(kGPBackground2Layout);
        kGPBackground2Layout.setHorizontalGroup(
            kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGPBackground2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbCCILogo)
                    .addComponent(tfNameCCI)
                    .addComponent(tfMobileNumCCI)
                    .addComponent(tfNationalityCCI)
                    .addComponent(cbGenderCCI, 0, 350, Short.MAX_VALUE)
                    .addComponent(tfEmailCCI)
                    .addComponent(lbNameCCI)
                    .addComponent(lbMobileNumCCI)
                    .addComponent(lbNationalityCCI)
                    .addComponent(lbGenderCCI)
                    .addComponent(lbEmailCCI))
                .addGap(136, 136, 136)
                .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfIDProofCCI)
                    .addComponent(tfAddressCCI)
                    .addComponent(tfCheckINDateCCI, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(lbIDProofCCI)
                    .addComponent(lbAddressCCI)
                    .addComponent(lbCheckINDateCCI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbBedCCI, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbRoomTypeCCI, 0, 350, Short.MAX_VALUE)
                        .addComponent(cbRoomNumCCI, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbPriceCCI, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPriceCCI)
                        .addComponent(lbRoomTypeCCI)
                        .addComponent(lbBedCCI)
                        .addComponent(lbRoomNumCCI))
                    .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(kbtnClearCCI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(kbtnAlloteRoomCCI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        kGPBackground2Layout.setVerticalGroup(
            kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGPBackground2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbCCILogo)
                .addGap(76, 76, 76)
                .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNameCCI)
                    .addComponent(lbIDProofCCI)
                    .addComponent(lbBedCCI))
                .addGap(18, 18, 18)
                .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNameCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIDProofCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBedCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMobileNumCCI)
                    .addComponent(lbAddressCCI)
                    .addComponent(lbRoomTypeCCI))
                .addGap(18, 18, 18)
                .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMobileNumCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAddressCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRoomTypeCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNationalityCCI)
                    .addComponent(lbCheckINDateCCI)
                    .addComponent(lbRoomNumCCI))
                .addGap(18, 18, 18)
                .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNationalityCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCheckINDateCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRoomNumCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGenderCCI)
                    .addComponent(lbPriceCCI))
                .addGap(18, 18, 18)
                .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGenderCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPriceCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGPBackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGPBackground2Layout.createSequentialGroup()
                        .addComponent(lbEmailCCI)
                        .addGap(18, 18, 18)
                        .addComponent(tfEmailCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kbtnAlloteRoomCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(kbtnClearCCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardCustomerCheckInLayout = new javax.swing.GroupLayout(cardCustomerCheckIn);
        cardCustomerCheckIn.setLayout(cardCustomerCheckInLayout);
        cardCustomerCheckInLayout.setHorizontalGroup(
            cardCustomerCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCustomerCheckInLayout.createSequentialGroup()
                .addComponent(kGPBackground2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cardCustomerCheckInLayout.setVerticalGroup(
            cardCustomerCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCustomerCheckInLayout.createSequentialGroup()
                .addComponent(kGPBackground2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpnMain.add(cardCustomerCheckIn, "card4");

        jpnContainer.add(jpnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1370, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbOpenMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOpenMenuMouseClicked
        // TODO add your handling code here:
        openMenubar();
    }//GEN-LAST:event_lbOpenMenuMouseClicked

    private void lbCloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMenuMouseClicked
        // TODO add your handling code here:
        closeMenubar();
    }//GEN-LAST:event_lbCloseMenuMouseClicked

    private void lbManageRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbManageRoomMouseClicked
        // TODO add your handling code here:
        cardTrangchu.setVisible(false);
        cardManageRoom.setVisible(true);
    }//GEN-LAST:event_lbManageRoomMouseClicked

    private void lbCustomerCheckInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCustomerCheckInMouseClicked
        // TODO add your handling code here:
//        cardTrangchu.setVisible(false);
//        cardTaikhoan.setVisible(true);
    }//GEN-LAST:event_lbCustomerCheckInMouseClicked

    private void lbHomePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHomePageMouseClicked
        // TODO add your handling code here:
        cardTrangchu.setVisible(true);
        cardManageRoom.setVisible(false);
    }//GEN-LAST:event_lbHomePageMouseClicked

    private void kbtnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtnAddRoomActionPerformed
        // TODO add your handling code here:
        String roomNo = tfRoomNumberM.getText();
        String roomType = (String) cbRoomTypeM.getSelectedItem();
        String bed = (String) cbBedM.getSelectedItem();
        String price = tfPriceM.getText();

        String Query = "INSERT INTO room VALUES('" + roomNo + "', '" + roomType + "', '" + bed + "', '" + price + "', 'Not Booked')";
        InsertUpdateDelete.setData(Query, "Successfully Updated");

        // Làm mới dữ liệu trên bảng sau khi thêm phòng thành công
        refreshRoomTable();

        // Chuyển sang card quản lý phòng
        CardLayout cardLayout = (CardLayout) jpnMain.getLayout();
        cardLayout.show(jpnMain, "cardManageRoom");
//        String roomNo = tfRoomNumberM.getText();
//        String roomType = (String) cbRoomTypeM.getSelectedItem();
//        String bed = (String) cbBedM.getSelectedItem();
//        String price = tfPriceM.getText();
//
//        String Query = "insert into room values('" + roomNo + "', '" + roomType + "', '" + bed + "', '" + price + "', 'Not Booked')";
//        InsertUpdateDelete.setData(Query, "Sucessfully Updated");
//
//        CardLayout cardLayout = (CardLayout) jpnMain.getLayout();
//        cardLayout.show(jpnMain, "cardManageRoom");
////        cardTrangchu.setVisible(false);
////        cardManageRoom.setVisible(true);
////        setVisible(false);
////        new manageRoom().setVisible(true);
    }//GEN-LAST:event_kbtnAddRoomActionPerformed

    private void cardManageRoomComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cardManageRoomComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jtbManageRoom.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ trong bảng
        ResultSet rs = Select.getData("select * from room");
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cardManageRoomComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardCustomerCheckIn;
    private javax.swing.JPanel cardManageRoom;
    private javax.swing.JPanel cardTrangchu;
    private javax.swing.JComboBox<String> cbBedCCI;
    private javax.swing.JComboBox<String> cbBedM;
    private javax.swing.JComboBox<String> cbGenderCCI;
    private javax.swing.JComboBox<String> cbRoomNumCCI;
    private javax.swing.JComboBox<String> cbRoomTypeCCI;
    private javax.swing.JComboBox<String> cbRoomTypeM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpnContainer;
    private javax.swing.JPanel jpnMain;
    private javax.swing.JPanel jpnMenuBar;
    private javax.swing.JPanel jpnSlideMenu;
    private javax.swing.JTable jtbManageRoom;
    private com.k33ptoo.components.KGradientPanel kGPBackground1;
    private com.k33ptoo.components.KGradientPanel kGPBackground2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KButton kbtnAddRoom;
    private com.k33ptoo.components.KButton kbtnAlloteRoomCCI;
    private com.k33ptoo.components.KButton kbtnClearCCI;
    private javax.swing.JLabel lbAddressCCI;
    private javax.swing.JLabel lbBedCCI;
    private javax.swing.JLabel lbBedM;
    private javax.swing.JLabel lbCCILogo;
    private javax.swing.JLabel lbCheckINDateCCI;
    private javax.swing.JLabel lbCloseMenu;
    private javax.swing.JLabel lbCustomerCheckIn;
    private javax.swing.JLabel lbCustomerCheckOut;
    private javax.swing.JLabel lbCustomerDetailsBill;
    private javax.swing.JLabel lbEmailCCI;
    private javax.swing.JLabel lbGenderCCI;
    private javax.swing.JLabel lbHomePage;
    private javax.swing.JLabel lbIDProofCCI;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbMRLogo;
    private javax.swing.JLabel lbManageRoom;
    private javax.swing.JLabel lbMobileNumCCI;
    private javax.swing.JLabel lbNameCCI;
    private javax.swing.JLabel lbNationalityCCI;
    private javax.swing.JLabel lbOpenMenu;
    private javax.swing.JLabel lbPriceCCI;
    private javax.swing.JLabel lbPriceM;
    private javax.swing.JLabel lbRoomNumCCI;
    private javax.swing.JLabel lbRoomNumberM;
    private javax.swing.JLabel lbRoomTypeCCI;
    private javax.swing.JLabel lbRoomTypeM;
    private javax.swing.JTextField tfAddressCCI;
    private javax.swing.JTextField tfCheckINDateCCI;
    private javax.swing.JTextField tfEmailCCI;
    private javax.swing.JTextField tfIDProofCCI;
    private javax.swing.JTextField tfMobileNumCCI;
    private javax.swing.JTextField tfNameCCI;
    private javax.swing.JTextField tfNationalityCCI;
    private javax.swing.JTextField tfPriceCCI;
    private javax.swing.JTextField tfPriceM;
    private javax.swing.JTextField tfRoomNumberM;
    // End of variables declaration//GEN-END:variables
}
