/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dacs1;

import contact.ChatContainer;
import static dacs1.EncryptByMD5.encryptMD5;
import java.awt.CardLayout;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import project.Select;
import java.sql.*;
import project.*;
import project.InsertUpdateDelete;

import java.io.File;
import java.io.IOException;
import java.net.Socket;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 *
 * @author ASUS
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
    String email;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnContainer = new javax.swing.JPanel();
        jpnLoginForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbLoginTitle = new javax.swing.JLabel();
        lbEmailL = new javax.swing.JLabel();
        lbPasswordL = new javax.swing.JLabel();
        tfEmailL = new javax.swing.JTextField();
        btnLoginL = new javax.swing.JButton();
        btnForgotPassL = new javax.swing.JButton();
        btnSignupL = new javax.swing.JButton();
        pwfPassL = new javax.swing.JPasswordField();
        kbtnContact = new com.k33ptoo.components.KButton();
        jpnSignupForm = new javax.swing.JPanel();
        kGPSignup = new com.k33ptoo.components.KGradientPanel();
        pwfPassS = new javax.swing.JPasswordField();
        lbSecurityQuesS = new javax.swing.JLabel();
        lbNameS = new javax.swing.JLabel();
        lbSignupTitle = new javax.swing.JLabel();
        lbAnswerS = new javax.swing.JLabel();
        lbAddressS = new javax.swing.JLabel();
        lbPasswordS = new javax.swing.JLabel();
        tfEmailS = new javax.swing.JTextField();
        tfNameS = new javax.swing.JTextField();
        lbEmailS = new javax.swing.JLabel();
        tfAddressS = new javax.swing.JTextField();
        tfAnswerS = new javax.swing.JTextField();
        jcbSecurityQuesS = new javax.swing.JComboBox<>();
        btnSignupS = new javax.swing.JButton();
        btnLoginS = new javax.swing.JButton();
        btnForgotPasswordS = new javax.swing.JButton();
        jpnForgotPasswordForm = new javax.swing.JPanel();
        kGPForgotPass = new com.k33ptoo.components.KGradientPanel();
        lbForgotPassTitle = new javax.swing.JLabel();
        lbEmailF = new javax.swing.JLabel();
        lbSecurityQuesF = new javax.swing.JLabel();
        lbAnswerF = new javax.swing.JLabel();
        lbNewPassF = new javax.swing.JLabel();
        tfEmailF = new javax.swing.JTextField();
        tfSecurityQuesF = new javax.swing.JTextField();
        tfAnswerF = new javax.swing.JTextField();
        btnSearchF = new javax.swing.JButton();
        btnSaveF = new javax.swing.JButton();
        btnSignupF = new javax.swing.JButton();
        btnLoginF = new javax.swing.JButton();
        pwfNewPassF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        jpnContainer.setOpaque(false);
        jpnContainer.setLayout(new java.awt.CardLayout());

        jpnLoginForm.setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.PNG"))); // NOI18N

        lbLoginTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbLoginTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbLoginTitle.setText("Login");

        lbEmailL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEmailL.setForeground(new java.awt.Color(255, 255, 255));
        lbEmailL.setText("Email:");

        lbPasswordL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPasswordL.setForeground(new java.awt.Color(255, 255, 255));
        lbPasswordL.setText("Password:");

        btnLoginL.setBackground(new java.awt.Color(153, 0, 0));
        btnLoginL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLoginL.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginL.setText("Login");
        btnLoginL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginLActionPerformed(evt);
            }
        });

        btnForgotPassL.setBackground(new java.awt.Color(153, 0, 0));
        btnForgotPassL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnForgotPassL.setForeground(new java.awt.Color(255, 255, 255));
        btnForgotPassL.setText("Forgot Password?");
        btnForgotPassL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPassLActionPerformed(evt);
            }
        });

        btnSignupL.setBackground(new java.awt.Color(153, 0, 0));
        btnSignupL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSignupL.setForeground(new java.awt.Color(255, 255, 255));
        btnSignupL.setText("Signup");
        btnSignupL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupLActionPerformed(evt);
            }
        });

        pwfPassL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        kbtnContact.setText("Contact");
        kbtnContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kbtnContact.setkHoverEndColor(new java.awt.Color(255, 255, 204));
        kbtnContact.setkHoverStartColor(new java.awt.Color(255, 153, 153));
        kbtnContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtnContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnLoginFormLayout = new javax.swing.GroupLayout(jpnLoginForm);
        jpnLoginForm.setLayout(jpnLoginFormLayout);
        jpnLoginFormLayout.setHorizontalGroup(
            jpnLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoginFormLayout.createSequentialGroup()
                .addContainerGap(480, Short.MAX_VALUE)
                .addGroup(jpnLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnLoginFormLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(lbLoginTitle))
                    .addGroup(jpnLoginFormLayout.createSequentialGroup()
                        .addGroup(jpnLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEmailL)
                            .addComponent(lbPasswordL))
                        .addGap(47, 47, 47)
                        .addGroup(jpnLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kbtnContact, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jpnLoginFormLayout.createSequentialGroup()
                                    .addComponent(btnLoginL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSignupL)
                                    .addGap(12, 12, 12)
                                    .addComponent(btnForgotPassL, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfEmailL, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pwfPassL, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(472, 472, 472))
            .addGroup(jpnLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnLoginFormLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpnLoginFormLayout.setVerticalGroup(
            jpnLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginFormLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(lbLoginTitle)
                .addGap(18, 18, 18)
                .addGroup(jpnLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmailL)
                    .addComponent(tfEmailL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpnLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPasswordL)
                    .addComponent(pwfPassL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoginL)
                    .addComponent(btnForgotPassL)
                    .addComponent(btnSignupL))
                .addGap(50, 50, 50)
                .addComponent(kbtnContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(jpnLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnLoginFormLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jpnContainer.add(jpnLoginForm, "card2");

        jpnSignupForm.setBackground(new java.awt.Color(255, 255, 255));

        kGPSignup.setkBorderRadius(0);
        kGPSignup.setkEndColor(new java.awt.Color(51, 255, 255));
        kGPSignup.setkGradientFocus(900);
        kGPSignup.setkStartColor(new java.awt.Color(255, 51, 255));
        kGPSignup.setOpaque(false);
        kGPSignup.setPreferredSize(new java.awt.Dimension(1372, 768));

        lbSecurityQuesS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSecurityQuesS.setText("Security Questions:");

        lbNameS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNameS.setText("Name:");

        lbSignupTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbSignupTitle.setText("Signup");

        lbAnswerS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAnswerS.setText("Answer:");

        lbAddressS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAddressS.setText("Address:");

        lbPasswordS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPasswordS.setText("Password:");

        tfEmailS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tfNameS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lbEmailS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEmailS.setText("Email:");

        tfAddressS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tfAnswerS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jcbSecurityQuesS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcbSecurityQuesS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is the name of your first pet?", "What was your first car?", "What elementary school did you attend?", "What is the name of the town where you were born?" }));

        btnSignupS.setBackground(new java.awt.Color(153, 0, 0));
        btnSignupS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSignupS.setForeground(new java.awt.Color(255, 255, 255));
        btnSignupS.setText("Signup");
        btnSignupS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupSActionPerformed(evt);
            }
        });

        btnLoginS.setBackground(new java.awt.Color(153, 0, 0));
        btnLoginS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLoginS.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginS.setText("Login");
        btnLoginS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSActionPerformed(evt);
            }
        });

        btnForgotPasswordS.setBackground(new java.awt.Color(153, 0, 0));
        btnForgotPasswordS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnForgotPasswordS.setForeground(new java.awt.Color(255, 255, 255));
        btnForgotPasswordS.setText("Forgot Password?");
        btnForgotPasswordS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPasswordSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGPSignupLayout = new javax.swing.GroupLayout(kGPSignup);
        kGPSignup.setLayout(kGPSignupLayout);
        kGPSignupLayout.setHorizontalGroup(
            kGPSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGPSignupLayout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addGroup(kGPSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGPSignupLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(lbSignupTitle))
                    .addGroup(kGPSignupLayout.createSequentialGroup()
                        .addGroup(kGPSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNameS)
                            .addComponent(lbEmailS)
                            .addComponent(lbPasswordS)
                            .addComponent(lbSecurityQuesS)
                            .addComponent(lbAnswerS)
                            .addComponent(lbAddressS))
                        .addGap(39, 39, 39)
                        .addGroup(kGPSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kGPSignupLayout.createSequentialGroup()
                                .addComponent(btnSignupS)
                                .addGap(18, 18, 18)
                                .addComponent(btnLoginS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnForgotPasswordS, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfAnswerS)
                            .addComponent(jcbSecurityQuesS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfEmailS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNameS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfAddressS)
                            .addComponent(pwfPassS, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(439, Short.MAX_VALUE))
        );
        kGPSignupLayout.setVerticalGroup(
            kGPSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGPSignupLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(lbSignupTitle)
                .addGap(41, 41, 41)
                .addGroup(kGPSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNameS)
                    .addComponent(tfNameS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(kGPSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmailS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmailS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGPSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPasswordS)
                    .addComponent(pwfPassS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGPSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSecurityQuesS)
                    .addComponent(jcbSecurityQuesS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGPSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAnswerS)
                    .addComponent(tfAnswerS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGPSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddressS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAddressS))
                .addGap(18, 18, 18)
                .addGroup(kGPSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignupS)
                    .addComponent(btnLoginS)
                    .addComponent(btnForgotPasswordS))
                .addContainerGap(262, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnSignupFormLayout = new javax.swing.GroupLayout(jpnSignupForm);
        jpnSignupForm.setLayout(jpnSignupFormLayout);
        jpnSignupFormLayout.setHorizontalGroup(
            jpnSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSignupFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGPSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnSignupFormLayout.setVerticalGroup(
            jpnSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSignupFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGPSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpnContainer.add(jpnSignupForm, "card3");

        jpnForgotPasswordForm.setBackground(new java.awt.Color(204, 255, 255));

        kGPForgotPass.setkBorderRadius(0);
        kGPForgotPass.setkEndColor(new java.awt.Color(51, 255, 255));
        kGPForgotPass.setkStartColor(new java.awt.Color(255, 51, 255));
        kGPForgotPass.setPreferredSize(new java.awt.Dimension(1372, 768));

        lbForgotPassTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbForgotPassTitle.setText("Forgot Password?");

        lbEmailF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEmailF.setText("Email:");

        lbSecurityQuesF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSecurityQuesF.setText("Security Questions:");

        lbAnswerF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAnswerF.setText("Answer:");

        lbNewPassF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNewPassF.setText("New Password:");

        tfEmailF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tfSecurityQuesF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tfAnswerF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnSearchF.setBackground(new java.awt.Color(153, 0, 0));
        btnSearchF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchF.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchF.setText("Search");
        btnSearchF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFActionPerformed(evt);
            }
        });

        btnSaveF.setBackground(new java.awt.Color(153, 0, 0));
        btnSaveF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSaveF.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveF.setText("Save");
        btnSaveF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveFActionPerformed(evt);
            }
        });

        btnSignupF.setBackground(new java.awt.Color(153, 0, 0));
        btnSignupF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSignupF.setForeground(new java.awt.Color(255, 255, 255));
        btnSignupF.setText("Signup");
        btnSignupF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupFActionPerformed(evt);
            }
        });

        btnLoginF.setBackground(new java.awt.Color(153, 0, 0));
        btnLoginF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLoginF.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginF.setText("Login");
        btnLoginF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginFActionPerformed(evt);
            }
        });

        pwfNewPassF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout kGPForgotPassLayout = new javax.swing.GroupLayout(kGPForgotPass);
        kGPForgotPass.setLayout(kGPForgotPassLayout);
        kGPForgotPassLayout.setHorizontalGroup(
            kGPForgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGPForgotPassLayout.createSequentialGroup()
                .addGap(573, 573, 573)
                .addComponent(lbForgotPassTitle)
                .addContainerGap(582, Short.MAX_VALUE))
            .addGroup(kGPForgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGPForgotPassLayout.createSequentialGroup()
                    .addGap(383, 383, 383)
                    .addGroup(kGPForgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbEmailF)
                        .addComponent(lbSecurityQuesF)
                        .addComponent(lbAnswerF)
                        .addComponent(lbNewPassF))
                    .addGap(54, 54, 54)
                    .addGroup(kGPForgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGPForgotPassLayout.createSequentialGroup()
                            .addComponent(btnSaveF)
                            .addGap(38, 38, 38)
                            .addComponent(btnSignupF)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLoginF))
                        .addComponent(tfEmailF)
                        .addComponent(tfSecurityQuesF)
                        .addComponent(tfAnswerF)
                        .addComponent(pwfNewPassF))
                    .addGap(42, 42, 42)
                    .addComponent(btnSearchF)
                    .addGap(384, 384, 384)))
        );
        kGPForgotPassLayout.setVerticalGroup(
            kGPForgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGPForgotPassLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(lbForgotPassTitle)
                .addContainerGap(529, Short.MAX_VALUE))
            .addGroup(kGPForgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGPForgotPassLayout.createSequentialGroup()
                    .addGap(282, 282, 282)
                    .addGroup(kGPForgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(kGPForgotPassLayout.createSequentialGroup()
                            .addGroup(kGPForgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbEmailF)
                                .addComponent(tfEmailF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSearchF))
                            .addGap(37, 37, 37)
                            .addComponent(lbSecurityQuesF))
                        .addComponent(tfSecurityQuesF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(38, 38, 38)
                    .addGroup(kGPForgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbAnswerF)
                        .addComponent(tfAnswerF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(38, 38, 38)
                    .addGroup(kGPForgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbNewPassF)
                        .addComponent(pwfNewPassF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(kGPForgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSaveF)
                        .addComponent(btnSignupF)
                        .addComponent(btnLoginF))
                    .addContainerGap(236, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jpnForgotPasswordFormLayout = new javax.swing.GroupLayout(jpnForgotPasswordForm);
        jpnForgotPasswordForm.setLayout(jpnForgotPasswordFormLayout);
        jpnForgotPasswordFormLayout.setHorizontalGroup(
            jpnForgotPasswordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnForgotPasswordFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGPForgotPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnForgotPasswordFormLayout.setVerticalGroup(
            jpnForgotPasswordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnForgotPasswordFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGPForgotPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpnContainer.add(jpnForgotPasswordForm, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginLActionPerformed
        // TODO add your handling code here:
        int check = 0;
        String email = tfEmailL.getText();
        String password = pwfPassL.getText();
        String sctPasss = encryptMD5(password);

        if (email.equals("") || password.equals("")) {
            check = 1;
            JOptionPane.showMessageDialog(null, "Every Field Is Required");
        } else if (email.equals("hms") && password.equals("admin")) {
            check = 2;
            setVisible(false);
            new adminHome().setVisible(true);
        } else {
            ResultSet rs = Select.getData("select * from users where email = '" + email + "' and password = '" + sctPasss + "'");
            try {
                if (rs.next()) {
                    check = 1;
                    if (rs.getString(7).equals("true")) {
                        setVisible(false);
                        new home().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Wait For Admin Approval");
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (check == 0) {
            JOptionPane.showMessageDialog(null, "Incorrect Email or Password");
        }


    }//GEN-LAST:event_btnLoginLActionPerformed

    private void btnSignupLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupLActionPerformed
        // TODO add your handling code here:
        jpnLoginForm.setVisible(false);
        jpnSignupForm.setVisible(true);
        jpnForgotPasswordForm.setVisible(false);
    }//GEN-LAST:event_btnSignupLActionPerformed

    private void btnForgotPassLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPassLActionPerformed
        // TODO add your handling code here:
        jpnSignupForm.setVisible(false);
        jpnLoginForm.setVisible(false);
        jpnForgotPasswordForm.setVisible(true);
    }//GEN-LAST:event_btnForgotPassLActionPerformed

    private void btnSignupSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupSActionPerformed
        // TODO add your handling code here:
        String name = tfNameS.getText();
        String email = tfEmailS.getText();
        String password = pwfPassS.getText();
        String sctPass = encryptMD5(password);

        String securityQuestion = (String) jcbSecurityQuesS.getSelectedItem();
        String answer = tfAnswerS.getText();
        String address = tfAddressS.getText();
        if (name.equals("") || email.equals("") || password.equals("") || answer.equals("") || address.equals(""))
            JOptionPane.showMessageDialog(null, "Every Field Is Required");
        else {
            String Query;
            Query = "insert into users values('" + name + "','" + email + "','" + sctPass + "','" + securityQuestion + "', '" + answer + "', '" + address + "','false')";
            InsertUpdateDelete.setData(Query, "Registered Successfully");
        
//            CardLayout cardLayout = (CardLayout) jpnContainer.getLayout();
//            cardLayout.show(jpnContainer, "jpnLoginForm"); 
            jpnSignupForm.setVisible(true);
            jpnLoginForm.setVisible(false);
            jpnForgotPasswordForm.setVisible(false);
        }
    }//GEN-LAST:event_btnSignupSActionPerformed

    private void btnLoginSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginSActionPerformed
        // TODO add your handling code here:
        jpnSignupForm.setVisible(false);
        jpnLoginForm.setVisible(true);
        jpnForgotPasswordForm.setVisible(false);
    }//GEN-LAST:event_btnLoginSActionPerformed

    private void btnForgotPasswordSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPasswordSActionPerformed
        // TODO add your handling code here:
        jpnSignupForm.setVisible(false);
        jpnLoginForm.setVisible(false);
        jpnForgotPasswordForm.setVisible(true);
    }//GEN-LAST:event_btnForgotPasswordSActionPerformed

    private void btnSearchFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFActionPerformed
        // TODO add your handling code here:
        int check = 0;
        email = tfEmailF.getText();
        if (email.equals("")) {
            check = 1;
            JOptionPane.showMessageDialog(null, "Email Field Is Required");
        } else {
            ResultSet rs = Select.getData("select * from users where email = '" + email + "'");
            try {
                if (rs.next()) {
                    check = 1;
                    tfSecurityQuesF.setEditable(false);
                    tfEmailF.setEditable(false);
                    tfSecurityQuesF.setText(rs.getString(4));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (check == 0)
            JOptionPane.showMessageDialog(null, "Incorrect Email");
    }//GEN-LAST:event_btnSearchFActionPerformed

    private void btnSaveFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveFActionPerformed
        // TODO add your handling code here:
        int check = 0;
        String securityQuestions = tfSecurityQuesF.getText();
        String answer = tfAnswerF.getText();
        String newPassword = pwfNewPassF.getText();
        if (answer.equals("") || newPassword.equals("")) {
            check = 1;
            JOptionPane.showMessageDialog(null, "All Field Is Required");
        } else {
            ResultSet rs = Select.getData("select * from users where email = '" + email + "' and securityQuestions = '" + securityQuestions + "' and answer = '" + answer + "'");
            try {
                if (rs.next()) {
                    check = 1;
                    InsertUpdateDelete.setData("update users set password = '" + newPassword + "' where email = '" + email + "'", "Password Set Successfully");

                    CardLayout cardLayout = (CardLayout) jpnContainer.getLayout();
                    cardLayout.show(jpnContainer, "jpnForgotPasswordForm"); // Chuyển về panel login
//                    jpnSignupForm.setVisible(false);
//                    jpnLoginForm.setVisible(false);
//                    jpnForgotPasswordForm.setVisible(true);
////                    CardLayout cardLayout = (CardLayout) jpnContainer.getLayout();
////                cardLayout.show(jpnContainer, "jpnForgotPasswordForm");
//                    setVisible(false);
////                    new forgotPassword().setVisible(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (check == 0)
            JOptionPane.showMessageDialog(null, "Incorrect Answer");
    }//GEN-LAST:event_btnSaveFActionPerformed

    private void btnSignupFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupFActionPerformed
        // TODO add your handling code here:
        jpnSignupForm.setVisible(true);
        jpnLoginForm.setVisible(false);
        jpnForgotPasswordForm.setVisible(false);
    }//GEN-LAST:event_btnSignupFActionPerformed

    private void btnLoginFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginFActionPerformed
        // TODO add your handling code here:
        jpnSignupForm.setVisible(false);
        jpnLoginForm.setVisible(true);
        jpnForgotPasswordForm.setVisible(false);
    }//GEN-LAST:event_btnLoginFActionPerformed

    private void kbtnContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtnContactActionPerformed
        // TODO add your handling code here:
        new ChatContainer().setVisible(true);
    }//GEN-LAST:event_kbtnContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgotPassL;
    private javax.swing.JButton btnForgotPasswordS;
    private javax.swing.JButton btnLoginF;
    private javax.swing.JButton btnLoginL;
    private javax.swing.JButton btnLoginS;
    private javax.swing.JButton btnSaveF;
    private javax.swing.JButton btnSearchF;
    private javax.swing.JButton btnSignupF;
    private javax.swing.JButton btnSignupL;
    private javax.swing.JButton btnSignupS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jcbSecurityQuesS;
    private javax.swing.JPanel jpnContainer;
    private javax.swing.JPanel jpnForgotPasswordForm;
    private javax.swing.JPanel jpnLoginForm;
    private javax.swing.JPanel jpnSignupForm;
    private com.k33ptoo.components.KGradientPanel kGPForgotPass;
    private com.k33ptoo.components.KGradientPanel kGPSignup;
    private com.k33ptoo.components.KButton kbtnContact;
    private javax.swing.JLabel lbAddressS;
    private javax.swing.JLabel lbAnswerF;
    private javax.swing.JLabel lbAnswerS;
    private javax.swing.JLabel lbEmailF;
    private javax.swing.JLabel lbEmailL;
    private javax.swing.JLabel lbEmailS;
    private javax.swing.JLabel lbForgotPassTitle;
    private javax.swing.JLabel lbLoginTitle;
    private javax.swing.JLabel lbNameS;
    private javax.swing.JLabel lbNewPassF;
    private javax.swing.JLabel lbPasswordL;
    private javax.swing.JLabel lbPasswordS;
    private javax.swing.JLabel lbSecurityQuesF;
    private javax.swing.JLabel lbSecurityQuesS;
    private javax.swing.JLabel lbSignupTitle;
    private javax.swing.JPasswordField pwfNewPassF;
    private javax.swing.JPasswordField pwfPassL;
    private javax.swing.JPasswordField pwfPassS;
    private javax.swing.JTextField tfAddressS;
    private javax.swing.JTextField tfAnswerF;
    private javax.swing.JTextField tfAnswerS;
    private javax.swing.JTextField tfEmailF;
    private javax.swing.JTextField tfEmailL;
    private javax.swing.JTextField tfEmailS;
    private javax.swing.JTextField tfNameS;
    private javax.swing.JTextField tfSecurityQuesF;
    // End of variables declaration//GEN-END:variables
}
